### ISSUE TITLE
Separação dos Arquivos

### ISSUE THREAD

**Issue by adrianosiqueira** [luisrguerra/devcpp-ptbr-mini-kit-cpp#1]
Boa iniciativa. Mas que tal separar cada tema em arquivos diferentes? Por exemplo, um arquivo **vetor.cpp** para conter vários exemplos de vetores, um arquivo **orientacaoObjeto.cpp** para exemplos com objetos, etc.

Isso melhoraria a organização do seu projeto à medida que ele cresce (e vai crescer, acredite), além de facilitar a procura de um tema específico.

**Comment by luisrguerra** [comment]
Agradeço o contato e sugestão. Irei futuramente criar categorias com os códigos separados para facilitar a procura
